### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by WML321** [AlexSartori/RISC-emV#1]
When I run main_gui(), there is a index error has been happend. The refer location is “riscemv\gui\MainWindow.py", line 18, in __init__”，and the tip is "self.init_emulator_components(self.emulators[0]), IndexError: list index out of range". I think the emulators is empry array.

**Comment by AlexSartori** [comment]
Hi @WML321, thanks for raising the issue. Did you close it because the problem is solved? Or do I need to look into the problem? I cannot seem to reproduce it on my machine.

**Comment by WML321** [comment]
@AlexSartori yes, I have solved the problem. The error occurs beacuse the imported package in the source file becomes a comment, resulting in the code not being executed.

**Comment by AlexSartori** [comment]
What do you mean exactly? How does that happen?

**Comment by WML321** [comment]
Sorry for the trouble, just started using github and some of the buttons don't function very well. I'm learning this open source project and in the process of learning, there are a few important library files that I commented out, that's why when I run the project, I get the error that happened to me at the very beginning.

**Comment by AlexSartori** [comment]
No worries at all! Feedback is always appreciated :)
